### ISSUE TITLE
Support other cache timeout times

### ISSUE THREAD

**Issue by dimo414** [dimo414/bash-cache#17]
**[Original report](https://bitbucket.org/dimo414/bash-cache/issue/17) by Pyetrek.**

----------------------------------------

By default it seems that the behaviour is to cache things for 10 seconds.  I don’t see a way to cache things for a different period of time.  Looking through the source bash file it seems that it is hard coded to 10 seconds.  Could we make this configurable through a configuration variable maybe?  That would be the easiest thing to do in the short term.  A longer term solution would involve making each function cached have configurable expiry time.

I normally use github and couldn’t figure out how to create a fork to make this change and then create a PR to merge it back, otherwise I would have.

Thanks

**Comment by chb0github** [comment]
You really should offer invalidation strategies as options. Like, a 10 second refresh is actually bad! In the case I gave in SoF it's sending thousands of API calls to bitbucket and they only allow so many in a period of time. I mean, I get the idea, and in many cases it makes perfect sense, but in my case that would be a problem. In some cases, it's even worse than for me because the throttling limits are account wide (like AWS)

**Comment by dimo414** [comment]
PRs are welcome :)

That said, I would be wary about using caching (via this library or otherwise) to interface with a throttled API; hiding side effects behind caches can easily lead to surprising or difficult-to-diagnose behavior (e.g. unexpected cache misses can still happen, and might kick you over your account limits). A caching layer may be "close enough" for some circumstances, but it's not providing the protection it sounds like you care about.

**Comment by dimo414** [comment]
This should work now! I'd appreciate help testing and validating everything works as intended, please file bugs if anything seems amiss.
